email_xpath=//*[@id='ctl00_ContentPlaceHolder1_Login_txtUsrEmailId']
next_xpath=//*[@id='ctl00_ContentPlaceHolder1_Login_btnCheckUserType']
password_xpath=//*[@id='ctl00_ContentPlaceHolder1_Login_txtUsrPwd']
signin_xpath=//*[@id='ctl00_ContentPlaceHolder1_Login_btnLogin']

action_xpath=//*[@id='divTpltClassNm_2914119']
create_xpath=//*[@id='btnCreate\']
field_xpath=//*[@id='custom@TextBox@VARCHAR39@NVARCHAR(MAX)']
save_xpath=//*[@id='btnSave']


